export const products = [
  { key: "electronics", label: "Electronics" },
  { key: "clothing", label: "Clothing" },
  { key: "makeup", label: "Makeup" },
  { key: "skincare", label: "Skincare" },
  { key: "footwear", label: "Footwear" },
  { key: "accessories", label: "Accessories" },
  { key: "homeAppliances", label: "Home Appliances" },
  { key: "furniture", label: "Furniture" },
  { key: "sports", label: "Sports Equipment" },
  { key: "toys", label: "Toys" },
  { key: "books", label: "Books" },
  { key: "stationery", label: "Stationery" },
  { key: "groceries", label: "Groceries" },
  { key: "automotive", label: "Automotive" },
  { key: "jewelry", label: "Jewelry" },
  { key: "garden", label: "Garden Supplies" },
  { key: "petSupplies", label: "Pet Supplies" },
  { key: "music", label: "Music Instruments" },
  { key: "health", label: "Health & Wellness" },
  { key: "babyProducts", label: "Baby Products" },
];
